version: '3'
services:
  productpage:
    image: g40/productpage
    container_name: g40-productpage
    volumes:
      - ./productpage:/app
    ports:
      - 8080:8080
  details:
    image: g40/details
    container_name: g40-details
    volumes:
      - ./details:/app
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    ports:
      - 9080:9080
  ratings:
    image: g40/ratings
    container_name: g40-ratings
    volumes:
      - ./ratings:/app
    ports:
      - 9080:9080

# Para poder ejecutar este docker-compose hay que seguir los siguientes pasos:
# 1. Crear las imagenes de cada uno de los servicios
# 2. Ejecutar el comando: $docker-compose up -d